version: '3'
services:
  reverse-proxy:
    image: traefik
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - "80:80" # the http port
      - "443:443" # the https port
      - "8080:8080" # the web ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # so that traefik can listen to docker event
      - ./traefik:/var/traefik/
      - ./cert:/cert
    command: --api --docker -c /var/traefik/traefik.toml
  bcoin:
    build:
      context: ./bcoin
      args:
        BCOIN_VERSION: v1.0.2
    restart: unless-stopped
    networks:
      - apps
      - traefik_proxy
    ports:
      #-- Mainnet
      # - "8333:8333"
      # - "8332:8332" # RPC
      # - "8334:8334" # Wallet
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC
      - "18334:18334" # Wallet
      #-- Regtest
      # - "48444:48444"
      # - "48332:48332" # RPC
      # - "48334:48334" # Wallet
      #-- Simnet
      # - "18555:18555"
      # - "18556:18556" # RPC
      # - "18558:18558" # Wallet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.entryPoints=https"
      - "traefik.node.frontend.rule=Host:test.bcoinjoemphilips.com;PathPrefix:/bcoin;PathPrefixStrip:/bcoin"
      - "traefik.wallet.frontend.rule=Host:test.bcoinjoemphilips.com;PathPrefix:/bcoin/wallet;PathPrefixStrip:/bcoin"
      - "traefik.backend=bcoin"
      - "traefik.node.port=18332"
      - "traefik.wallet.port=18334"
      - "traefik.protocol=http"
    command: node /code/bcoin/bin/node --prefix=/root/.bcoin
    volumes:
      - ~/.bpanel-docker/bcoin:/root/.bcoin
  bpanel:
    build:
      context: ./bpanel
    restart: unless-stopped
    depends_on:
      - bcoin
    networks:
      - apps
      - traefik_proxy
    environment:
      # Need this to tell the bpanel client
      # how to communicate with the bcoin node
      # in docker
      BPANEL_NODE_HOST: bcoin
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - ~/.bpanel-docker/bpanel:/root/.bpanel
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.entryPoints=https"
      - "traefik.frontend.port=8000"
      - "traefik.frontend.rule=Host:bpanel.bcoinjoemphilips.com"
    ## Only MacOSX users need --watch-poll
    ## the client-id says to use the config created by the
    ## bcoin docker services
    command: server --dev --watch-poll --client-id=testnet

networks:
  traefik_proxy:
    external: true
  apps:
    external: true
