logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [[entryPoints.https.tls.certificates]]
    certFile = "/cert/server.crt"
    keyFile = "/cert/server.key"
# [acme]
# email = "joemphilips@gmail.com"
# acmeLogging = true
# storage = "acme.json"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
# entryPoint = "https"
#   [acme.httpChallenge]
#   entryPoint = "http"
# [[acme.domains]]
#  main = "test.bcoinjoemphilips.com"
[traefikLog]
  filePath = "/var/traefik/traefik.log"
[accessLog]
  filePath = "/var/traefik/access.log"
[docker]
# endpoint = "unix:///var/run/docker.sock"
domain = "test.bcoinjoemphilips.com"
watch = true
#swarmmode = true
# [backend]
