logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [[entryPoints.https.tls.certificates]]
    certFile = "/cert/server.crt"
    keyFile = "/cert/server.key"
# [acme]
# email = "joemphilips@gmail.com"
# acmeLogging = true
# storage = "acme.json"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
# entryPoint = "https"
#   [acme.httpChallenge]
#   entryPoint = "http"
# [[acme.domains]]
#  main = "test.bcoinjoemphilips.com"
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
